name: traffic_dbt
version: "1.0.0"
config-version: 2

profile: traffic_dbt
model-paths: ["models"]
clean-targets: ["target", "dbt_packages"]

models:
  traffic_dbt:
    staging:
      +schema: staging
      +materialized: view
    analytics:
      +schema: analytics
      +materialized: table

